### ISSUE TITLE
RC2 Release

### ISSUE THREAD

**Issue by SUB-BJ** [SubstratumNetwork/SubstratumNode#103]
Release RC2 baby! Yeah!

**Comment by substratumservices** [comment]
Found issue #273 while prepping this release.  We'll need to make a new build including the fix and move the tag when we do the release.  Here are the notes I made so far of the cards included in the release:

**SC-960: Allow for persistence of node descriptor in the GUI** - added a checkbox for optionally keeping the last neighbor node descriptor
**SC-958: Make earning address part of the persistent model for GUI to be displayed in the input of the settings form** - this allows the earning address to be pre-populated in the GUI if it has already been set up in SubstratumNode
**SC-969: GUI Input field loses generated node descriptor** - fixes a bug where the node descriptor generated by your node would get cleared if you visited a different screen in the GUI
**SC-941: GasPrice should be adjustable to account for new minimums** - added a screen in the GUI to allow for adjucting the gas price
**SC-905: Routing Logic for origin-only nodes on perimeter (GitHub issue #52)** - fixed an issue causing origin-only nodes to prevent good nodes from routing
**SC-257: Sign Binaries for macOS**
**SC-972: Change annotations to use target_os** - this allows for cross-compiling (compiling for a different OS)
**SC-947: Allow blockchain service url to be specified in GUI** - this enables GUI users to specify how SubstratumNode is supposed to connect to the blockchain
**SC-411: Sign Electron for Windows**
**SC-980: Settings menu takes too long to load** - fixed an issue causing the settings menu in the GUI to take a noticably long time to load
**SC-959: Allow earning address to be different than the one for consuming** - added a checkbox for optionally specifying a different derivation path for the earning address when generating or recovering your consuming wallet through the GUI
**SC-977: node_logfile_does_not_belong_to_root_integration test does not work** - fixed functionality intended to make sure the log file is created with the correct file permissions
