### ISSUE TITLE
node connects to two bootstrap servers causing panic

### ISSUE THREAD

**Issue by brianmanahan** [SubstratumNetwork/SubstratumNode#11]
SubstratumNode 0.4.2
commit:  b5b416975972151cc79ac4ecab867e11205c3abf

In a 3 system configuration, 2 bootstrap servers and one client connecting to both causes panics on all 3

1. start up a bootstrap server on two different nodes

sudo ./node/target/release/SubstratumNode --dns_servers 1.1.1.1 --ip x.x.x.x --port_count 2 --log_level debug --node_type bootstrap

SubstratumNode local descriptor: mA3ZqnHPgwUzDfZ/NcGzgZpHIjDL2pyMvTV7GhQ4tmY:x.x.x.x:33172,42658

SubstratumNode local descriptor: gbKmme/BPmWLxoJTSrZdNYlgNNtaN37Uf7T0MqWAdYE:x.x.x.x:39723,47299

2. Start up a node and use two (2) neighborhood stanzas pointing to the above bootstrap nodes.

sudo ./node/target/release/SubstratumNode --dns_servers 1.1.1.1 --ip x.x.x.x --port_count 2 --log_level debug --neighbor mA3ZqnHPgwUzDfZ/NcGzgZpHIjDL2pyMvTV7GhQ4tmY:x.x.x.x:33172,42658 --neighbor gbKmme/BPmWLxoJTSrZdNYlgNNtaN37Uf7T0MqWAdYE:x.x.x.x:39723,47299

**Expected behavior**
I didn't know what to expect, but I didn't expect my two bootstrap servers to panic along with my node.  

**Screenshots**
![bam panic](https://user-images.githubusercontent.com/19829239/53145425-042c1180-3555-11e9-9826-556ee91d7599.PNG)

**Log files**
[node00-bootstrap- bam panic.txt](https://github.com/SubstratumNetwork/SubstratumNode/files/2887760/node00-bootstrap-.bam.panic.txt)
[node01-bootstrap- bam panic.txt](https://github.com/SubstratumNetwork/SubstratumNode/files/2887761/node01-bootstrap-.bam.panic.txt)
[rpi -bam panic.txt.txt](https://github.com/SubstratumNetwork/SubstratumNode/files/2887762/rpi.-bam.panic.txt.txt)

**Device Details (please complete the following information):**
bootstrap node 00 - AWS EC2 Instance in USW2 running CentOS 7.x 
bootstrap node 01 - AWS EC2 Instance in USW2 running CentOS 7.x
node - Raspberry Pi3, latest raspian OS.  

**Additional context**
When we were testing, we found that with a 3 node cluster, you must first setup one bootstrap server, connect one of the nodes to it (single neighborhood parameter), then the 3rd node can connect to both of the first nodes.

**Comment by DarthStrom** [comment]
Created SC-773 to address this.

**Comment by SUB-BJ** [comment]
A condition is being hit that isn't implemented yet. This is why the panic says "not yet implemented." We will make sure that this is implemented in some fashion to resolve this prior to MVP. There's a comment on that line of code that says "we don't know this node, so we should assume it is not a bootstrap node."

Thanks!

**Comment by substratumservices** [comment]
We were able to reproduce this by bootstrapping to two bootstrap-only nodes.  However, bootstrapping from either one bootstrap-only node and a standard node or bootstrapping from two standard nodes works fine.  For now, we are removing this from MVP and suggest not using two bootstrap-only nodes and instead use a single bootstrap-only node and a standard node or just two standard nodes.

**Comment by SUB-BJ** [comment]
This is no longer valid.
