### ISSUE TITLE
[Feature] [GUI] Display Node Descriptor

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#14]
**Is your feature request related to a problem? Please describe.**
In the most recent GUI, one can connect to a neighbor by entering the corresponding _neighbor node descriptor_ into the wizard form. However, the GUI doesn't display node's own descriptor. This is essential if one wants to share the portal to others.

**Describe the solution you'd like**
Display the _neighbor node descriptor_ of user's node.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SUB-BJ** [comment]
This is related to SC-772: Ability to copy Node Descriptor for sharing and is MVP

**Comment by substratumservices** [comment]
SC-772 Is complete and deployed to the open source repo.
