### ISSUE TITLE
[Feature] [GUI] Make settings more accessible

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#15]
**Is your feature request related to a problem? Please describe.**
In the latest GUI, a wizard form is displayed upon node launch. However, this setting is for one-time only. The settings of IP, descriptor and wallet address cannot be changed unless restarting the node app.

**Describe the solution you'd like**
Embed the functionality of wizard form into the setting button.

**Describe alternatives you've considered**
Any way to bring back the wizard form.

**Additional context**
None

**Comment by SUB-BJ** [comment]
I created Epic SC-771: Settings Panel Enhancements in order to capture specific settings features. Some will be MVP and others may not. More to come.

**Comment by SUB-BJ** [comment]
This has been completed to a point and there are more settings coming in the future.
