### ISSUE TITLE
[Bug] [GUI] Wizard form is taking arbitrary string

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#16]
**SubstratumNode Version**
0.4.c
Issue exists as of commit 935379a9e7693918790e5c9d6f3c099e361d6bbb

**Describe the bug**
The three fields in Node wizard form (MY EXTERNAL IP ADDRESS, NEIGHBOR NODE DESCRIPTOR, WALLET ADDRESS) currently accept arbitrary string.

**To Reproduce**
1. Start SubstratumNode compiled from latest commit
2. The wizard form shows up
3. Enter any characters into the three fields
4. Click 'Save'
5. No error

**Expected behavior**
Warning for IP, Descriptor and Wallet Address in wrong format.
Users won't be allowed to save incorrect info.

**Screenshots**
None

**Log files**
None

**Device Details (please complete the following information):**
 - Laptop
 - Ubuntu 18.04

**Additional context**
None

**Comment by DarthStrom** [comment]
This will be addressed by SC-760

**Comment by SUB-BJ** [comment]
This is merged in migrating to the public repo now.
