### ISSUE TITLE
[Feature] [GUI] Provide Statistics Center

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#20]
**Is your feature request related to a problem? Please describe.**
A dedicated and unified statistics center to display info that users are interested in.

**Describe the solution you'd like**
Make a statistics center in GUI, to show info such as: historical traffic, service accounting, neighborhood diagram, and etc.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SUB-BJ** [comment]
This is related to SC-768: Make Node Stats Visible. There will most likely be some break down of this card to more defined features like accounting for routing and exit services for example. But we will start with this one. My gut says there will be some MVP work broken down that will be included related to this one. Thanks!

**Comment by SUB-BJ** [comment]
This work has been completed for RC1. However, there are possibly more to come by v1.
