### ISSUE TITLE
Ubuntu bootstrap & node panics after ~24 hours

### ISSUE THREAD

**Issue by brianmanahan** [SubstratumNetwork/SubstratumNode#22]
Commit c1be53bbd38c00a37cba791a87d1b0872b3c8f74

**Describe the bug**
Approximately after 24 hours, the bootstrap panics and the process dies. 

**To Reproduce**
1. Start screen session 
screen -S bootstrap

2. Start Bootstrap with:
time sudo ./node/target/release/SubstratumNode --dns_servers 1.1.1.1 --ip x.x.x.x --port_count 2 --log_level debug --node_type bootstrap

3. Reconnect to screen session 24 hours later.  
screen -dr

4. Observe thread error and cursor is back at command prompt:
thread 'tokio-runtime-worker-0' panicked at 'Connected stream has no peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Expected behavior**
I expect the bootstrap server & node to stay up and remain available until I have chosen to stop the service.  

**Screenshots**
Screenshot illustrates stdout of bootstrap running in screen session with above bootstrap service start command.  
![ubuntu-bootstrap-panic-03072019](https://user-images.githubusercontent.com/19829239/54007351-222d7080-4116-11e9-8c58-ef6f41722b1f.PNG)

**Log files**
Last lines of  /tmp/SubstratumNode.log on Ubuntu)
[SubstratumNode.log](https://github.com/SubstratumNetwork/SubstratumNode/files/2944381/SubstratumNode.log)

AWS EC2 Ubuntu 18.04 (system fully updated)
Linux substratumnode00.somedomain.us 4.15.0-1033-aws #35-Ubuntu SMP Wed Feb 6 13:29:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
rustc 1.33.0 (2aa4c46cf 2019-02-28)
build-essential
nodejs 11.10.1 (with nvm)
yarn 1.13.0
libssl-dev
pkg-config

I have been able to get this to occur on both, bootstrap and regular nodes (connected to same bootstrap) on Ubuntu 18.04.  The panic'ing seems to be happening more frequently with the last few commits.

**Comment by SUB-BJ** [comment]
Thanks @brianmanahan!

**Comment by SUB-BJ** [comment]
Thanks @brianmanahan! This is related to SC-774: Ubuntu boosdtrap & node panics after ~ 24 hours.

**Comment by brianmanahan** [comment]
23rd hour mark screenshots attached with bootstrap on top.  node on bottom.  

![bootstrap-node-panics03082019](https://user-images.githubusercontent.com/19829239/54065820-9af60080-41da-11e9-8bff-1de49fc4a0f3.PNG)

**Comment by brianmanahan** [comment]
tracking "connected stream has no peer_addr" on commit 4a280a9 from node connecting to bootstrap server.

**Comment by SUB-BJ** [comment]
This has been addressed.
