### ISSUE TITLE
Governance should enforce dttm format on debug log entries

### ISSUE THREAD

**Issue by brianmanahan** [SubstratumNetwork/SubstratumNode#23]
All Versions

When running nodes via command line on linux (ubuntu, centos, raspberry pi's), with log_level set to debug, I am seeing that in the /tmp/SubstratumNode.log file, only lines listed as INFO contain the dttm formatting "2019-03-08 02:32:23.916".  DEBUG lines do not contain the date/time entries.  

**To Reproduce**
1.) start bootstrap with --log_level debug
2.) tail -f /tmp/SubstratumNode.log

/tmp/SubstratumNode.log should contain DEBUG lines with datetime stamps

INFO [<unnamed>] 2019-03-07 02:27:13.112 ThreadId(1): INFO: Bootstrapper: SubstratumNode local descriptor: WmKeXFf7RAD5WC0MLUOF4aWmqMNa1SmJUqH/lPq0jx4:X.X.X.X:38293,55378
DEBUG [tokio_reactor] adding I/O source: 0
DEBUG [tokio_reactor::registration] scheduling Read for: 0
DEBUG [tokio_reactor] adding I/O source: 4194305
DEBUG [tokio_reactor::registration] scheduling Read for: 1
DEBUG [tokio_reactor] adding I/O source: 8388610
DEBUG [tokio_reactor::registration] scheduling Read for: 2
DEBUG [tokio_reactor] adding I/O source: 12582915
DEBUG [tokio_reactor::registration] scheduling Read for: 3
DEBUG [tokio_reactor] adding I/O source: 16777220
DEBUG [tokio_reactor::registration] scheduling Read for: 4
DEBUG [tokio_core::reactor] consuming notification queue
INFO [<unnamed>] 2019-03-07 02:27:13.113 ThreadId(2): DEBUG: Proxy Client: Handling BindMessage
INFO [<unnamed>] 2019-03-07 02:27:13.114 ThreadId(2): INFO: Proxy Client: Adding DNS server: 1.1.1.1

**Comment by SUB-BJ** [comment]
This is related to SC-775: Governance should enforce dttm format on debug log entries

**Comment by SUB-BJ** [comment]
This has been addressed.
