### ISSUE TITLE
[Bug] Log_level parameter info also reports debug info

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#26]
**SubstratumNode Version**
Commit f5d67ec

**Describe the bug**
when the node is started with the parameter --loglevel info, the log screen/file also shows debug info.

**To Reproduce**
Run Node: sudo SubstratumNode/node/target/release/SubstratumNode --dns_servers 1.1.1.1 --ip a.b.c.d. --port_count 2 **--log_level info** --data_directory xxxx/yyyy --neighbor {...} --neighbor {...}

**Expected behavior**
Expected to only see loglevel info and lower (warn/error)

**Screenshots**
![loglevel info](https://user-images.githubusercontent.com/23551316/54037779-3bd6c280-41bf-11e9-8915-cb2e7518fb28.png)

**Log files**
See screenshot

**Device Details (please complete the following information):**
Any

**Additional context**
The Warn loglevel shows no info/debug/trace info on the screen or in the logfile. That seems to be working.

**Comment by SUB-BJ** [comment]
This is related to Bug SC-431: Log level filter does not work

**Comment by SUB-BJ** [comment]
We have significantly revamped logging. There is still more we'd like to get to but it's pretty good right now. :) Thanks!
