### ISSUE TITLE
[Feature] [GUI] Support multi ports

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#27]
**Is your feature request related to a problem? Please describe.**
There is no way to set **port_count** in current GUI. The default is 1, while this setting is configurable in command line.

**Describe the solution you'd like**
Provide this option in settings.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SUB-BJ** [comment]
This is being closed because the concept of clandestine ports is going away in favor of simply sending traffic over ports 80 and 443.
