### ISSUE TITLE
[Feature] Advanced port settings

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#28]
**Is your feature request related to a problem? Please describe.**
As far as I understand, currently ports in the range of 10000-65535 are randomly selected and opened (in addition to the required ports 80, 443 and so on) for communication. Users may want an option of narrowing the choice into one, several, or a smaller range.

What's more, maybe the required web ports 80 and 443 can be optional and editable too, to suit a wider range of circumstances.

**Describe the solution you'd like**
Provide advanced port settings, in command line and GUI.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SUB-BJ** [comment]
This is being closed because the concept of clandestine ports is going away in favor of simply sending clandestine traffic over ports 80 and 443.
