### ISSUE TITLE
[Feature] Add support for Telegraf for collecting metrics

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#29]
**Is your feature request related to a problem? Please describe.**
Would like to have insights in metrics like #of nodes in the Hood, their status, amount of data transported/routeed, the Accountant info etc.

**Describe the solution you'd like**
Telegraf is an agent for collecting, processing, aggregating, and writing metrics.
Design goals are to have a minimal memory footprint with a plugin system so that developers in the community can easily add support for collecting metrics.

**Additional context**

**Comment by SUB-BJ** [comment]
We have some stories we are looking to create regarding specific metrics that will be available in Node directly. Those stats will be smaller stories related to Epic SC-768: Make Node Stats Visible.

I also created an epic for this request, assuming there would be one-to-many features to make this possible. This is related to Epic SC-784: Metrics interface for Telegraf. This is not MVP.
