### ISSUE TITLE
"unrecognized stream key" appearing a lot in logs when consuming

### ISSUE THREAD

**Issue by substratumservices** [SubstratumNetwork/SubstratumNode#305]
There are three places in the Proxy Server in which we purge stream keys. One in whenever DNS resolution fails, one is when a packet with last_data set is received, and one is when the Proxy Server receives a StreamShutdownMsg, which if I'm not mistaken, happens whenever a StreamReader within that node shuts down. Based on my testing, the majority of the unrecognized stream keys are a result of the second case, when a key is purged upon receiving a last_data packet.
My theory is that since packets don't get sorted until they reach the StreamWriter, the last_data packet is being received before prior packets with a lower sequence number. Therefore, once those earlier packets are received, the stream key has already been purged from the Proxy Server. This theory is backed up by the fact that commenting out the line that purges stream keys in the last_data case causes almost all of the unrecognized stream keys to disappear.
Therefore, to fix that, we somehow need to deal with the fact that we may see the last packet before prior packets. I still haven't thought of a way to do this in the Proxy Server. Originally I was going to look into having the StreamWriter notify the Proxy Server in this case. (Now that I think about it, maybe it already does. If it also sends a StreamShutdownMsg once it processes the last_data packet, after sorting, then we could simply remove the last_data check in the ProxyServer.)
A smaller portion of the unrecognized stream keys seems to come from the StreamShutdownMsg. I suspect that this is not actually an error and should be handled differently. If I understand correctly, StreamShutdownMsg is when a direct connection to the node is closed. Therefore, if, for example, a connection to the browser closes before receiving the last_data packet, we will drop any data that is left and complain about the stream key being unrecognized. This seems like
a non-erroneous case. Hope that's understandable and helpful!

**Comment by DarthStrom** [comment]
This was only reproducible when failing to port forward.  I did notice another issue when trying to consume with the port properly forwarded which I will create a new bug card for.

**Comment by dnwiebe** [comment]
I'm skeptical about the packet-ordering issue. StreamKeys should only exist between Proxy Server and Proxy Client, not at any lower level. Neither StreamHandlerPool nor StreamWriter nor StreamReader should be poodling around with StreamKeys. And by the time data gets to Proxy Server and Proxy Client, it should be properly ordered.

I'm thinking that it may actually be connected with GH-307. Before GH-307, when a TCP stream terminated, the termination was taken care of appropriately at the StreamReader/StreamHandlerPool level, and then a message sent to the Neighborhood to modify the NeighborhoodDatabase. However, the Neighborhood was not handling that message appropriately, and the NeighborhoodDatabase wasn't being modified, resulting in dead nodes continuing to be represented as connected. It could be that the Neighborhood was composing, or continuing to honor preexisting, routes through those Nodes, and thus demanding streams that no longer existed.

Or...wait! What if there's an established route for a TLS connection, and the connection keeps using that route, and then one of the Nodes in the route goes down? If that Node was the first or last relay Node, that'd produce a StreamKey error in either the Proxy Client or the Proxy Server.

More stuff to investigate.
