### ISSUE TITLE
[Bug] thread 'main' panicked at 'Connected stream has no peer_addr...'

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#33]
**SubstratumNode Version**
f39396b566d8a24378c265993d32dda23657a9a4

**Describe the bug**
thread 'main' panicked at 'Connected stream has no peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Panic in Arbiter thread, shutting down system.

After 12 hours (rough estimate) this error was on the console screen.

**Device Details (please complete the following information):**
Ubuntu 16.04 LTS server

**Comment by SUB-BJ** [comment]
This is related to Production Defect SC-797: [Bug] thread 'main' panicked at 'Connected stream has no peer_addr...' #33.

Being considered for MVP.

**Comment by SUB-BJ** [comment]
This bug is MVP as of April 1, 2019. Not joking.

**Comment by substratumservices** [comment]
We tried to reproduce this by having a network running over night and did not see a panic.  This may have been resolved incidentally.  Closing for now, if it happens again please open a new issue.
