### ISSUE TITLE
[Bug] [GUI] Wizard form saves null input

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#36]
**SubstratumNode Version**
SubstratumNode 0.4.3

**Describe the bug**
In GUI version 0.4.3, wizard form shows up upon launch, asking for "My External Address", "Neighbor Node Descriptor" and "Wallet Address". The info is critical for running SubstratumNode and joining in SubstratumNetwork.

It good that all three fields are designed to be able to recognize any error input. The 'Save' button is grayed out when entered info is in incorrect format.

However, when the fields are left blank, Node still saves the null info and allow users to go to next step.

**To Reproduce**
1. Open up SubstratumNode GUI
2. Fill nothing into the three fields in the wizard form
3. Click 'Save'
4. Node saves and goes to the next step

**Expected behavior**
Node shouldn't save and allow user to go to next step when essential info is missing. The 'Save' button should be grayed out with null info. Or, a warning message should pop out. Or provide another button, like 'Ask me later' to by pass this step.

**Screenshots**
None

**Log files**
None

**Device Details (please complete the following information):**
Not applicable

**Additional context**
None

**Comment by SUB-BJ** [comment]
This issue relates to Production Defect SC-800: Wizard form saves null input values. 

Form handling is an MVP item.

**Comment by SUB-BJ** [comment]
The team spoke about this today and this was intentional so that zero hop functionality is still possible. We are discussing future uses for zero hop functionality and deciding what this means to the GUI.
