### ISSUE TITLE
Can't copy paste to Text Inputs in the node UI. 

### ISSUE THREAD

**Issue by jchudzynski** [SubstratumNetwork/SubstratumNode#37]
**SubstratumNode Version**
Need the full version of SubstratumNode (e.g. SubstratumNode 0.4.2)
0.4.3
Mac OS 10.14.2
**Describe the bug**

Can't copy paste to Text Inputs in the node UI. 

**To Reproduce**
1. Copy any text.
2. Open Node and try to paste using right click or key shortcuts (CMD+V)
3. Nothing happens
**Expected behavior**

Text will be pasted into the text inputs 

**Screenshots**

**Log files**
Include any relavent logging information. (e.g. /tmp/SubstratumNode.log on Ubuntu)

**Device Details (please complete the following information):**
 - Device Type [e.g. laptop, desktop, mobile phone, router, IoT]
 - OS name and version (Windows 8, OSX 10.14.2, Ubuntu 16.04, Arch 1.0, etc.)
 - Application [e.g. chrome, safari]

**Additional context**

**Comment by SUB-BJ** [comment]
This relates to product defect SC-801: Can't copy paste to Text Inputs in the node UI.

This is an MVP item.

**Comment by substratumservices** [comment]
Fix(SC-801) is in master now.
