### ISSUE TITLE
[Bug] [GUI] Node descriptor does disappear after switching Node off

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#38]
**SubstratumNode Version**
SubstratumNode 0.4.3 GUI

**Describe the bug**
When Node is switched off, Node descriptor still shows in UI.

**To Reproduce**
1. Start SubstratumNode
2. Click on 'Serving', Node shows descriptor text
3. click on 'Off'
4. Node descriptor remains while Node is off.

**Expected behavior**
When Node is switched off, text in Node Descriptor field should disappear.

**Screenshots**
None

**Log files**
None

**Device Details (please complete the following information):**
Windows Server 2016

**Additional context**
This kind of glitch can be easily dealt with if the UI uses a state reactive implementation, such as React Redux, or equivalent. Developers only need to focus on the data, and the connection between data and UI elements.

**Comment by SUB-BJ** [comment]
This relates to production defect SC-802: Node descriptor fails to reset after Node is turned off

This is MVP
