### ISSUE TITLE
[Bug] [UI] Feedback link is likely outdated

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#39]
**SubstratumNode Version**
SubstratumNode 0.4.3 GUI

**Describe the bug**
'Send Feedback / Report an Error' links to an out-dated feedback page.

**To Reproduce**
1. Start SubstratumNode
2. Click on ⚙️ icon
3. Click 'Send Feedback / Report an Error'
4. Get directed to an [outdated feedback page](https://substratum.net/open-beta-survey/) which was designed for '0.3.0 Testing Survey'

**Expected behavior**
Feedback should be directed to an up-to-date webpage where all feedbacks are actively monitored, or, just redirect to [issues on GitHub](https://github.com/SubstratumNetwork/SubstratumNode/issues)

**Screenshots**
None

**Log files**
None

**Device Details (please complete the following information):**
Not applicable

**Additional context**
None

**Comment by SUB-BJ** [comment]
This relates to production defect SC-803: Node Feedback form needs updated for general use or removed

**Comment by SUB-BJ** [comment]
We are going to point to the Github issues tab instead.

**Comment by SUB-BJ** [comment]
This has been addressed months ago.
