### ISSUE TITLE
[Feature] [Website] Redesign download section

### ISSUE THREAD

**Issue by humicro** [SubstratumNetwork/SubstratumNode#41]
**Is your feature request related to a problem? Please describe.**
Current download links of SubstratumNode official releases on [open-beta](https://substratum.net/open-beta/) page is confusing. I've seen at least three instances where people downloaded command line binary and complained GUI didn't work.

The major issue is, people think "Download SubstratumNode - WINDOWS" is just a title, and the 'Download Binary' is the accompanied link.

**Describe the solution you'd like**
Redesign the download page to differentiate the releases according to OS and GUI/CLI, accompanied with detailed description/explanation.

**Describe alternatives you've considered**

**Additional context**
None

**Comment by SUB-BJ** [comment]
This relates to SC-805: Redesign Bloated Website Downloads Section

**Comment by SUB-BJ** [comment]
Abram took a stab at the redesign on this. It's subtle but better. We also have future plans for more changes where we depend on what's in GitHub releases.
