### ISSUE TITLE
503 error - routing problem

### ISSUE THREAD

**Issue by Yozhi179** [SubstratumNetwork/SubstratumNode#43]
**SubstratumNode Version**
dowloaded from substratum.net - version 0.4.3

**Describe the bug**
Program installed and only seems to be  working, but I get Error 503 Routing problem or some pages Firefox says "performing TLS hanshake to e.g. wikipedia.org and it never opens and timeout.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Substarumnode.log in temp directory has 0 bytes.

log from Brian M node, which he said confirms that I got connected

ytes for 178.40.0.82:50612; transmitting via Hopper
INFO [<unnamed>] 2019-03-30 18:48:14.243 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator has no more data framed
INFO [<unnamed>] 2019-03-30 18:48:14.255 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 2687-byte chunk from port 41574
INFO [<unnamed>] 2019-03-30 18:48:14.255 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Adding 2687 bytes to discriminator
INFO [<unnamed>] 2019-03-30 18:48:14.255 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 2004 bytes of clandestine data
INFO [<unnamed>] 2019-03-30 18:48:14.256 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator framed and unmasked 2004 b
ytes for 178.40.0.82:50612; transmitting via Hopper
INFO [<unnamed>] 2019-03-30 18:48:14.256 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator has no more data framed
INFO [<unnamed>] 2019-03-30 18:48:14.298 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 1402-byte chunk from port 41574
INFO [<unnamed>] 2019-03-30 18:48:14.298 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Adding 1402 bytes to discriminator
INFO [<unnamed>] 2019-03-30 18:48:14.299 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator has no more data framed
INFO [<unnamed>] 2019-03-30 18:48:14.300 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 953-byte chunk from port 41574
INFO [<unnamed>] 2019-03-30 18:48:14.300 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Adding 953 bytes to discriminator
INFO [<unnamed>] 2019-03-30 18:48:14.301 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 1753 bytes of clandestine data
INFO [<unnamed>] 2019-03-30 18:48:14.301 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator framed and unmasked 1753 b
ytes for 178.40.0.82:50612; transmitting via Hopper
INFO [<unnamed>] 2019-03-30 18:48:14.302 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator has no more data framed
INFO [<unnamed>] 2019-03-30 18:48:14.309 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 2355-byte chunk from port 41574
INFO [<unnamed>] 2019-03-30 18:48:14.309 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Adding 2355 bytes to discriminator
INFO [<unnamed>] 2019-03-30 18:48:14.309 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 1753 bytes of clandestine data
INFO [<unnamed>] 2019-03-30 18:48:14.310 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator framed and unmasked 1753 b
ytes for 178.40.0.82:50612; transmitting via Hopper
INFO [<unnamed>] 2019-03-30 18:48:14.310 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator has no more data framed
INFO [<unnamed>] 2019-03-30 18:48:14.310 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 1402-byte chunk from port 41574
INFO [<unnamed>] 2019-03-30 18:48:14.311 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Adding 1402 bytes to discriminator
INFO [<unnamed>] 2019-03-30 18:48:14.311 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator has no more data framed
INFO [<unnamed>] 2019-03-30 18:48:14.319 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 949-byte chunk from port 41574
INFO [<unnamed>] 2019-03-30 18:48:14.319 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Adding 949 bytes to discriminator
INFO [<unnamed>] 2019-03-30 18:48:14.320 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 1752 bytes of clandestine data
INFO [<unnamed>] 2019-03-30 18:48:14.320 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator framed and unmasked 1752 b
ytes for 178.40.0.82:50612; transmitting via Hopper
INFO [<unnamed>] 2019-03-30 18:48:14.320 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Discriminator has no more data framed
INFO [<unnamed>] 2019-03-30 18:48:18.753 ThreadId(0): DEBUG: StreamReader for 178.40.0.82:50612: Read 1402-byte chunk from port 41574

**Device Details (please complete the following information):**
- small notebook UMAX VisionBook 13WA Pro with only one network adapter
- almost fresh win10 1809 install with all updates
- windows firewall and antivirus disabled, no other installed
- in router DMZ set to my internal ip address 

**Additional context**

**Comment by SUB-BJ** [comment]
This is an outdated issue and has since been resolved.

**Comment by Yozhi179** [comment]
B.J. for me it is still not resolved, I am getting it even on last 0.4.7 version. I tried to use several descriptors including pinned ones.
