### ISSUE TITLE
[Bug] Panic in Arbiter thread, shutting down system.

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#46]
**SubstratumNode Version**
0.4.3 commit c201dbb09c76d9c42a780e0f73da17ecd4ae32c2

**Describe the bug**
After a couple of hours, the Node panic with this error

**To Reproduce**
Run the node, connect to three Neighbors and wait.
The bug also appears when connected to 1 or 2 neighbors

**Screenshots**
![Panic in Arbiter](https://user-images.githubusercontent.com/23551316/55581807-1be2e200-571e-11e9-912f-cc3bd735c370.png)

**Device Details (please complete the following information):**
Ubuntu 18.04 LTS server on Azure.

**Comment by SUB-BJ** [comment]
This is related to SC-907. Thank you @meizenga!

**Comment by SUB-BJ** [comment]
We think this is good to go now as it's many versions old and we've done lots of testing since then to validate this error isn't showing up. However, if you can reproduce this let us know and we will reopen the issue.
