### ISSUE TITLE
[Bug]: SubstratumNode Compiling fails on Ubuntu

### ISSUE THREAD

**Issue by XBITSwitzerland** [SubstratumNetwork/SubstratumNode#48]
**SubstratumNode Version**
v0.4.4

**Describe the bug**
I cloned the Git Repository of Substratum Node and try to run it on linux. Get a Error.

**To Reproduce**
1. git clone https://github.com/SubstratumNetwork/SubstratumNode.git
2. ci/all.sh

**Expected behavior**
It should not give an Error

**Log files**
```
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test dns_resolve_failure_test'
BUILD_RESULT=$?
+ BUILD_RESULT=101
chmod -R 777 "$CI_DIR/../target"
+ chmod -R 777 /home/dany/SubstratumNode/node/ci/../target
exit "$BUILD_RESULT"
+ exit 101
```

**Device Details (please complete the following information):**
Linux Ubuntu

**Comment by SUB-BJ** [comment]
Please try the latest version. Also, don't feel that you have to run the ci/all.sh as we run them internally on all supported platforms. Instead, build what you need and connect to the testing community in telegram for assistance. They can help you.
