### ISSUE TITLE
_yarn lint_ not working correctly in node-ui directory 

### ISSUE THREAD

**Issue by BGbot6** [SubstratumNetwork/SubstratumNode#51]
**SubstratumNode Version**
Node Version 0.4.4 - Last Commit: 0492192

**Describe the bug**
When running the _ci/all.sh_ or the _yarn lint_ command from the SubstratumNode/node-ui directory, 

**To Reproduce**
1. Type _cd SubstratumNode/node-ui_
2. Run the _ci/all.sh_ or _yarn run lint_ command  

**Expected behavior**
I expected the node-ui to correctly run

**Screenshots**
![Screenshot 2019-05-07 19:32:36](https://user-images.githubusercontent.com/46912528/57339417-8319fa80-70ff-11e9-804c-272c16f76a3a.png)

**Log files**
Include any relavent logging information. (e.g. /tmp/SubstratumNode.log on Ubuntu)

**Device Details (please complete the following information):**
 - I have received this error message on both my laptop running Ubuntu 18LTS, and my Raspberry Pi 3B+ running Rasbian/Stretch 32bit ARMV71. 
 - Ubuntu 18LTS and Rasbian/Stretch 32bit 
 
**Additional context**
I have installed yarn and nodejs on both of my systems in order to execute the node-ui. I have passed _yarn upgrade_ on both systems multiple times, as well as updated nodejs to version 12.2.0 and yarn to version 1.15.2. I can pass the _yarn start_ command in the same node-ui directory and the following UI will pop up, but it is blank and unusable with the following error message: ~/SubstratumNode/node-ui$ yarn start
yarn run v1.15.2
warning ../../package.json: No license field
$ electron .
19:44:30.620 › dns_utility failed:  Error accessing ~/SubstratumNode/node-ui/dist/static/binaries/dns_utility: No such file or directory

![Screenshot 2019-05-07 19:46:11](https://user-images.githubusercontent.com/46912528/57339727-cf196f00-7100-11e9-8555-3c9884e96b21.png)

**Comment by SUB-BJ** [comment]
This is related to issue SC-908

**Comment by SUB-BJ** [comment]
This seems like an environment or execution issue. Please work with the testing group in telegram and they can help verify what is happening.
