### ISSUE TITLE
Window 7 error

### ISSUE THREAD

**Issue by coder82** [SubstratumNetwork/SubstratumNode#53]
On windows 7 there is currently an error when clicking on Serving or Consuming (0.4.6).
I used this node descriptor:

mPwkK6O8WB+g3lBluVTbfis+I9A+ihzI4LX1BkNXTgo:52.11.186.12:10000
I did setup the external address correctly and also the dns to 127.0.0.1.

[screenshot1](https://i.imgur.com/aYSgBBT.png)
[screenshot2](https://i.imgur.com/0Pfqcaq.png)

I never tried subnode from command line, I always tried from the GUI but, altough sometimes I was able to serve, I was never able to consume, and when I was, my IP was not hidden.

**Comment by SUB-BJ** [comment]
There is not enough information here to help you. I would suggest connecting with our testing group in telegram because they really do help each other.
