### ISSUE TITLE
OS 10048

### ISSUE THREAD

**Issue by dimitristzam** [SubstratumNetwork/SubstratumNode#54]
**SubstratumNode Version**
Need the full version of SubstratumNode (e.g. SubstratumNode 0.4.2)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Include any relavent logging information. (e.g. /tmp/SubstratumNode.log on Ubuntu)

**Device Details (please complete the following information):**
 - Device Type [e.g. laptop, desktop, mobile phone, router, IoT]
 - OS name and version (Windows 8, OSX 10.14.2, Ubuntu 16.04, Arch 1.0, etc.)
 - Application [e.g. chrome, safari]

**Additional context**

**Comment by dimitristzam** [comment]
![Χωρίς τίτλο](https://user-images.githubusercontent.com/9869382/58581492-5b2e3a80-8258-11e9-998f-64f1e457f0f9.png)

**Comment by SUB-BJ** [comment]
You provided no detail in the template. However, looks like all you need to do is read the following document.

https://github.com/SubstratumNetwork/SubstratumNode/blob/master/node/docs/PORT_53.md
