### ISSUE TITLE
[Feature] Add support for DNS over TLS

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#55]
**Is your feature request related to a problem? Please describe.**
The level of anonymity can be enhanced when DNS traffic encrypted.

**Describe the solution you'd like**
DNS over TLS can be found in RFC7858

**Additional context**
Node to node traffic is encrypted, however the DNS data exchange between the exit node and the configured DNS server is still in plain text. DNS over TLS encrypts the data sent between the exit node and the DNS server. 

CloudFlare has some nice info here: https://developers.cloudflare.com/1.1.1.1/dns-over-tls/

**Comment by SUB-BJ** [comment]
This is related to story SC-909. Thanks @meizenga!
