### ISSUE TITLE
[Bug] Panic in Arbiter thread, shutting down system.

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#56]
**SubstratumNode Version**
Commit 853db0e  

**Describe the bug**
thread 'main' panicked at 'not yet implemented', src/blockchain/blockchain_interface.rs:76:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Panic in Arbiter thread, shutting down system.

**To Reproduce**
Start the Node. Wait 1 Hour, and the error appears on the console screen.

**Expected behavior**
Node keeps running and does not panic.

**Device Details (please complete the following information):**
- CentOS 7.6
- Ubuntu 18.04 LTS

**Comment by substratumservices** [comment]
This issue has been tracked down and fixed.
