### ISSUE TITLE
Windows DNS 127.0.0.1 bug - DNS switching

### ISSUE THREAD

**Issue by Yozhi179** [SubstratumNetwork/SubstratumNode#58]
**SubstratumNode Version**
I experienced it was on versions 0.4.3 -0.4.7 - downloaded from substartum.net

**Describe the bug**
- when you run a node on GUI windows 10, put IP, descriptor and start.
it looks like dns is set to 127.0.0.1 but OS  somehow doesn't acknowledge it at once. That is why many windows users claim that they can browse for a few minutes (not routing over substratum network) and then browsing normally stops (if sub neighborhood is not working correctly) . To really make OS acknowledge the DNS 127.0.0.1  at once, I have to go to network setting open the TCP/IPv4 properties (DNS 127.0.0.1 is already filled there) and confirm with OK. 
- same goes for the other way around. when you turn off the node. DNS 127.0.0.1 disappears from network settings, but OS doesn't acknowledges it. you have to go open TCP/IPv4 properties and confirm it to be able to browse normally again.
- simply DNS switching doesn't work correctly although it appears so.- needs manual confirmation.

**Comment by SUB-BJ** [comment]
We've had a card for this open for some time now. It's SC-837: Fix Card for SC-291 Windows DNS Utility Issue. (SC-291 was a research card we played to investigate the issue)

Here's the description: At present, dns_utility uses the Winreg library to modify the Registry. Change the Windows version of dns_utility to use the Windnslibrary instead: perhaps specifically the DnsServiceRegister and DnsServiceDeRegister entry points.

Speculation: this may result in a reduction of the delay between the time dns_utility subvert is executed and the time when all new TCP and UDP connections are made using the DNS at 127.0.0.1:53. We haven’t experimented.

**Comment by Yozhi179** [comment]
To do it quickly for now I'm using following command in CMD. it has immediate effect.
"netsh interface ipv4 add dnsserver "Ethernet" address=127.0.0.1 index=1"

**Comment by SUB-BJ** [comment]
This has been updated. Try again.

https://bit.ly/2XJyB7c
