### ISSUE TITLE
HW32.Packed. false positive detected

### ISSUE THREAD

**Issue by coder82** [SubstratumNetwork/SubstratumNode#62]
**SubstratumNode Version**
0.4.8

When running the installer under Bkav AV, it detects HW32.Packed.
This is a false positive, but still try to clear it if you can, people are very diffident and might discard thoe whole thing if they see one red flag.

![image](https://user-images.githubusercontent.com/26207876/61115341-8b413e00-a492-11e9-945b-534ba48e286f.png)

**Comment by SUB-BJ** [comment]
Unfortunately, it's a weakness in anti-virus software providers across lots of programs. It manifests from using the sqlite database for one. We certainly can't remove that. :) Thanks for the heads up though!
