### ISSUE TITLE
[Feature] [GUI] Dynamic neighborhood visualization

### ISSUE THREAD

**Issue by wrho** [SubstratumNetwork/SubstratumNode#65]
**Is your feature request related to a problem? Please describe.**
Currently the neighborhood topology is available to the user as CLI log of a DOT digraph.

**Describe the solution you'd like**
Dynamic neighborhood visualization with a JavaScript library like D3.js or vis.js directly in the GUI.

**Describe alternatives you've considered**
Textual output of the digraph in GUI which can easily be copy & pasted onto an external website for visualization. Might become available on [community wiki](https://substratum.wiki)

**Additional context**
There were several network visualizations on twitter when v0.4.2 came out by Micro (D3.js) and myself (vis.js, Cytoscape, Gephi). Just found my way on GitHub to share the code for anyone interested.

Code example with vis.js in form of a single page website (paste digraph, visualize the network): [neighborhood_visualization.zip](https://github.com/SubstratumNetwork/SubstratumNode/files/3450793/neighborhood_visualization.zip)
![animation1](https://user-images.githubusercontent.com/53513476/62200449-ba5a1980-b385-11e9-811f-f08cf30200bc.gif)

**Comment by sub-abram** [comment]
I have created a feature request in our system #SC-968. We will add it to our backlog and determine if/when it fits into our prioritization.

**Comment by wrho** [comment]
Thank you Steve and Jon for bringing this feature to life!
