### ISSUE TITLE
No Wallet-Password Prompt in Command line

### ISSUE THREAD

**Issue by Crypt0-Kiwi** [SubstratumNetwork/SubstratumNode#68]
Running on Latest commit: 607ee89

I had previously used --generate-wallet to create a seed phrase and two wallets with the default derivation paths.

Now when running SubstratumNode from commandline I am not prompted for a wallet password

**To Reproduce**
1. Stop all instances of SubNode and delete node-data.db file
2. Run --recover-wallet with --data-directory specified (I use another path to a user directory under my home filepath)
3. I **do not** enter a mnemonic passphrase (leave this blank)
4. Enter a wallet password
5. Type in the mnemonic seed words
6. this returns me to commandline
7. Run SubstratumNode --dump-config to see proper entries of correct wallet address in the output (so seed words are correct)
8. run SubstratumNode command, but DO NOT specify a --wallet-password parameter
9. Node initializes but routing attempt throw error 'no consuming wallet specified'

![8133623e-2d02-4318-a4e3-9a04ca7336ae](https://user-images.githubusercontent.com/52662521/62606008-646e0e80-b94f-11e9-8aad-b6cc42fd2611.jpg)

I have not stored the wallet password in any script used to run the Node command, or in the config.toml

NOTE:
Re-running the SubstratumNode command with the --wallet-password parameter typed out seems to work

**Device Details (please complete the following information):**
 - Environment - Raspbian latest updated OS on Raspberry Pi (ARM)

**Comment by sub-abram** [comment]
I created a production defect in Epic SC-964. We will try to reproduce this defect and resolve the issue.

**Comment by sub-abram** [comment]
If you want to be prompted for a wallet password you must add the --wallet-password argument without passing a value. The ability to omit --wallet-password argument allows a GUI to provide a wallet password later.
