### ISSUE TITLE
[Bug] RC1 Windows GUI: "Unable to talk to the Substratum Node, consider restarting it"

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#71]
**SubstratumNode Version**
RC1 build from source

**Describe the bug**
The Windows GUI stops displaying Debt and Credits. An error shows in the GUI

**To Reproduce**
1. Start Node
2. Wait a minute
3. Financials Tab is showing "Unable to talk to the Substratum Node, consider restarting it"

**Expected behavior**
The actual Debt and Credits

**Screenshots**
![image](https://user-images.githubusercontent.com/23551316/62611459-ea656780-b905-11e9-9bdf-051a78d12fb4.png)

**Comment by sub-abram** [comment]
I have created a production defect issue SC-965. We will attempt to reproduce this issue and resolve it.
