### ISSUE TITLE
SubNode must be smart to handle custom DNS configurations

### ISSUE THREAD

**Issue by Alino** [SubstratumNetwork/SubstratumNode#80]
some users on telegram had issues with this.
one guy had a VPN client installed which sets custom DNS for him.
SubstratumNode could not deal with this.

Suggestion:
When you click on serve or consume (when substratum node has to change DNS settings to localhost)
And if the DNS settings of the user are using some custom configuration.
Then there should pop up a confirmation dialog with a question "Do you really want to serve/consume? This is going to change your DNS settings"
with a checkbox "don't show this message again"
and buttons "yes" and "no"

So clicking yes would override the custom DNS settings after saving it somewhere, so that it can be recovered later when turning off the node.

PS: I know that this was design decision not to mess with user's DNS configuration. But I believe my proposal makes better sense for most users and mass adoption. Otherwise it will be a block for some percentage of users who use VPNs or their friends set their DNS to 8.8.8.8

**Comment by SUB-BJ** [comment]
We already have an epic full of features around doing this differently. We plan on changing that paradigm since we are beginning to allow proxy capabilities versus subverting the entire machines DNS.
