### ISSUE TITLE
[Feature] [GUI] show new public IP address when consuming

### ISSUE THREAD

**Issue by Alino** [SubstratumNetwork/SubstratumNode#81]
To be more informative and increase the confidence of the user that consuming works, a new public IP address should be displayed to the user

![image](https://user-images.githubusercontent.com/763194/62746278-0d4f6300-ba4f-11e9-9f2a-d2fd68fc41de.png)

in addition, location (country) would be great.

**Comment by SUB-BJ** [comment]
We have no desire for you to care about other people's IP Addresses. It's actually more of a security risk for those other users. It works as designed and we aim to keep things as anonymous as possible.

**Comment by sterlingbeason** [comment]
> 
> 
> We have no desire for you to care about other people's IP Addresses. It's actually more of a security risk for those other users. It works as designed and we aim to keep things as anonymous as possible.

Security Through Obscurity (STO) like this isn't substantially beneficial to a system. What stops an end user from using on of the thousands of "What's my IP?" services to reveal this information?

**Comment by SUB-BJ** [comment]
Nothing stops it right now. It's not security through obscurity more than we aren't trying to tell the world all the information about the network that's possible, in a helpful GUI field, from a single node's experience.

**Comment by Alino** [comment]
I have to disagree, because this is not affecting the security.
The user can still obtain his new public IP address, from OS or external websites. All websites he visits know this information anyway.
What's the reason to try to make the substratum node blind about his IP address?
It's better if this info is available for him, so that he knows he is protected. (increase confidence that the product works)

It is a good practice, and good VPN clients do this.

![image](https://user-images.githubusercontent.com/763194/62765281-17458600-ba90-11e9-9382-dad0cc5d9f78.png)

**Comment by SUB-BJ** [comment]
Check out the CORES topology introduction video for more information.

**Comment by Alino** [comment]
I have reviewed that video again after a year or so, but I don't know how that explains why we cannot have this feature. Am I missing something?

**Comment by SUB-BJ** [comment]
Watch again.
