### ISSUE TITLE
[Feature] Release Nightly binaires

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#85]
**Is your feature request related to a problem? Please describe.**
Release Nightly binaries so the community can test the latest version

**Describe the solution you'd like**
Provide Nightly binaries on this Github repo. You can use GitHub Actions to trigger a build from a new commit.

**Describe alternatives you've considered**
You can always build yourself from source, however thats not easy for the regular user.

**Comment by Alino** [comment]
this would speed up development process. We could quickly test and confirm if the code changes work.

**Comment by SUB-BJ** [comment]
We like this and have a fully open-source epic with many stories to make this possible. We are going to move forward with this. Thank you for your feature request!
