### ISSUE TITLE
[Feature] Add ability to change external IP address

### ISSUE THREAD

**Issue by Alino** [SubstratumNetwork/SubstratumNode#87]
Why we need this?

**scenario:**
_Given that the user is consuming and his external IP address is changed
When the user navigates to a webserver where his new IP address is in blacklist (banned)
And the webserver returns http code 200 (success), but shows an informative message "Your IP address is restricted from using this web"
And the user clicks on a button in Substratum node to change his IP address
And he refreshes the restricted website
Then the website works with no restrictions_

So we need this mainly as a workaround for the given scenario.
But it can be also useful for changing identity (Tor has this feature too, VPNs too)

One user named Sterling, made a custom mod to do this.
![323ceb9b-ff9a-45ec-bc73-567a494a](https://user-images.githubusercontent.com/763194/62856769-101fb180-bcf6-11e9-9643-edb5db87f5b1.gif)

related to https://github.com/SubstratumNetwork/SubstratumNode/issues/81

**Comment by SUB-BJ** [comment]
It's only doing a poll and getting the IP of the current GEOIP location for that individual request and no more. We are building the intelligence into the SubstratumNode so that the user doesn't have to do it manually. Besides that, this feature is opposed to what we are trying to do as stated in the video on the CORES topology. Reduce the potential attack surface and increase user anonymity.

**Comment by Alino** [comment]
Are you saying that each network request can have a different IP address?
In that case I am afraid it will break client-server communication in such cases where the server is monitoring IP changes and blocks requests if IP change was detected.

**Comment by SUB-BJ** [comment]
Don't be afraid. Yes. That is what I am saying. For TLS it sustains the same exit node for during the session.

**Comment by Alino** [comment]
well in that case it is starting to make more sense now to me. Thanks.

I think it will be a big challenge to make the nodes smart to understand that a page is restricted when there is no http error code, so that it would use a proper exit node which is not blacklisted.

**Comment by SUB-BJ** [comment]
It already automatically deprioritizes Nodes from performing exit services when they fail to procure the content. It was a bit challenging.

**Comment by Alino** [comment]
that's great, I can only imagine how hard it was to be able to detect when a page fails to procure the content.
